//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllergyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllergyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoKnownAllergies" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="Y|N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SourceOfInformation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="P|C"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}EffectiveDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ExpirationDate" minOccurs="0"/>
 *         &lt;element name="AdverseEvent" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
 *                   &lt;element name="CodeListQualifier" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="LD"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DrugProductCoded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
 *                   &lt;element name="CodeListQualifier" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="ND|MF|RX|RT|UN|UP"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReactionCoded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
 *                   &lt;element name="CodeListQualifier" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="LD"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SeverityCoded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
 *                   &lt;element name="CodeListQualifier" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="LD"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllergyType", propOrder = {
    "noKnownAllergies",
    "sourceOfInformation",
    "effectiveDate",
    "expirationDate",
    "adverseEvent",
    "drugProductCoded",
    "reactionCoded",
    "severityCoded"
})
public class AllergyType {

    @XmlElement(name = "NoKnownAllergies")
    protected String noKnownAllergies;
    @XmlElement(name = "SourceOfInformation")
    protected String sourceOfInformation;
    @XmlElement(name = "EffectiveDate")
    protected DateType effectiveDate;
    @XmlElement(name = "ExpirationDate")
    protected DateType expirationDate;
    @XmlElement(name = "AdverseEvent")
    protected AllergyType.AdverseEvent adverseEvent;
    @XmlElement(name = "DrugProductCoded")
    protected AllergyType.DrugProductCoded drugProductCoded;
    @XmlElement(name = "ReactionCoded")
    protected AllergyType.ReactionCoded reactionCoded;
    @XmlElement(name = "SeverityCoded")
    protected AllergyType.SeverityCoded severityCoded;

    /**
     * Gets the value of the noKnownAllergies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoKnownAllergies() {
        return noKnownAllergies;
    }

    /**
     * Sets the value of the noKnownAllergies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoKnownAllergies(String value) {
        this.noKnownAllergies = value;
    }

    /**
     * Gets the value of the sourceOfInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfInformation() {
        return sourceOfInformation;
    }

    /**
     * Sets the value of the sourceOfInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfInformation(String value) {
        this.sourceOfInformation = value;
    }

    /**
     * ALG-030 07
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setEffectiveDate(DateType value) {
        this.effectiveDate = value;
    }

    /**
     * ALG-030 36
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setExpirationDate(DateType value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the adverseEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyType.AdverseEvent }
     *     
     */
    public AllergyType.AdverseEvent getAdverseEvent() {
        return adverseEvent;
    }

    /**
     * Sets the value of the adverseEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyType.AdverseEvent }
     *     
     */
    public void setAdverseEvent(AllergyType.AdverseEvent value) {
        this.adverseEvent = value;
    }

    /**
     * Gets the value of the drugProductCoded property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyType.DrugProductCoded }
     *     
     */
    public AllergyType.DrugProductCoded getDrugProductCoded() {
        return drugProductCoded;
    }

    /**
     * Sets the value of the drugProductCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyType.DrugProductCoded }
     *     
     */
    public void setDrugProductCoded(AllergyType.DrugProductCoded value) {
        this.drugProductCoded = value;
    }

    /**
     * Gets the value of the reactionCoded property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyType.ReactionCoded }
     *     
     */
    public AllergyType.ReactionCoded getReactionCoded() {
        return reactionCoded;
    }

    /**
     * Sets the value of the reactionCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyType.ReactionCoded }
     *     
     */
    public void setReactionCoded(AllergyType.ReactionCoded value) {
        this.reactionCoded = value;
    }

    /**
     * Gets the value of the severityCoded property.
     * 
     * @return
     *     possible object is
     *     {@link AllergyType.SeverityCoded }
     *     
     */
    public AllergyType.SeverityCoded getSeverityCoded() {
        return severityCoded;
    }

    /**
     * Sets the value of the severityCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllergyType.SeverityCoded }
     *     
     */
    public void setSeverityCoded(AllergyType.SeverityCoded value) {
        this.severityCoded = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
     *         &lt;element name="CodeListQualifier" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="LD"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemDescriptionLong",
        "itemNumber",
        "codeListQualifier"
    })
    public static class AdverseEvent {

        @XmlElement(name = "ItemDescriptionLong", required = true)
        protected String itemDescriptionLong;
        @XmlElement(name = "ItemNumber")
        protected String itemNumber;
        @XmlElement(name = "CodeListQualifier")
        protected String codeListQualifier;

        /**
         * Gets the value of the itemDescriptionLong property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDescriptionLong() {
            return itemDescriptionLong;
        }

        /**
         * Sets the value of the itemDescriptionLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDescriptionLong(String value) {
            this.itemDescriptionLong = value;
        }

        /**
         * Gets the value of the itemNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNumber() {
            return itemNumber;
        }

        /**
         * Sets the value of the itemNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNumber(String value) {
            this.itemNumber = value;
        }

        /**
         * Gets the value of the codeListQualifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeListQualifier() {
            return codeListQualifier;
        }

        /**
         * Sets the value of the codeListQualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeListQualifier(String value) {
            this.codeListQualifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
     *         &lt;element name="CodeListQualifier" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="ND|MF|RX|RT|UN|UP"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemDescriptionLong",
        "itemNumber",
        "codeListQualifier"
    })
    public static class DrugProductCoded {

        @XmlElement(name = "ItemDescriptionLong", required = true)
        protected String itemDescriptionLong;
        @XmlElement(name = "ItemNumber")
        protected String itemNumber;
        @XmlElement(name = "CodeListQualifier")
        protected String codeListQualifier;

        /**
         * Gets the value of the itemDescriptionLong property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDescriptionLong() {
            return itemDescriptionLong;
        }

        /**
         * Sets the value of the itemDescriptionLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDescriptionLong(String value) {
            this.itemDescriptionLong = value;
        }

        /**
         * Gets the value of the itemNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNumber() {
            return itemNumber;
        }

        /**
         * Sets the value of the itemNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNumber(String value) {
            this.itemNumber = value;
        }

        /**
         * Gets the value of the codeListQualifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeListQualifier() {
            return codeListQualifier;
        }

        /**
         * Sets the value of the codeListQualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeListQualifier(String value) {
            this.codeListQualifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
     *         &lt;element name="CodeListQualifier" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="LD"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemDescriptionLong",
        "itemNumber",
        "codeListQualifier"
    })
    public static class ReactionCoded {

        @XmlElement(name = "ItemDescriptionLong", required = true)
        protected String itemDescriptionLong;
        @XmlElement(name = "ItemNumber")
        protected String itemNumber;
        @XmlElement(name = "CodeListQualifier")
        protected String codeListQualifier;

        /**
         * Gets the value of the itemDescriptionLong property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDescriptionLong() {
            return itemDescriptionLong;
        }

        /**
         * Sets the value of the itemDescriptionLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDescriptionLong(String value) {
            this.itemDescriptionLong = value;
        }

        /**
         * Gets the value of the itemNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNumber() {
            return itemNumber;
        }

        /**
         * Sets the value of the itemNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNumber(String value) {
            this.itemNumber = value;
        }

        /**
         * Gets the value of the codeListQualifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeListQualifier() {
            return codeListQualifier;
        }

        /**
         * Sets the value of the codeListQualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeListQualifier(String value) {
            this.codeListQualifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemDescriptionLong"/>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ItemNumber" minOccurs="0"/>
     *         &lt;element name="CodeListQualifier" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="LD"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemDescriptionLong",
        "itemNumber",
        "codeListQualifier"
    })
    public static class SeverityCoded {

        @XmlElement(name = "ItemDescriptionLong", required = true)
        protected String itemDescriptionLong;
        @XmlElement(name = "ItemNumber")
        protected String itemNumber;
        @XmlElement(name = "CodeListQualifier")
        protected String codeListQualifier;

        /**
         * Gets the value of the itemDescriptionLong property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemDescriptionLong() {
            return itemDescriptionLong;
        }

        /**
         * Sets the value of the itemDescriptionLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemDescriptionLong(String value) {
            this.itemDescriptionLong = value;
        }

        /**
         * Gets the value of the itemNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNumber() {
            return itemNumber;
        }

        /**
         * Sets the value of the itemNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNumber(String value) {
            this.itemNumber = value;
        }

        /**
         * Gets the value of the codeListQualifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeListQualifier() {
            return codeListQualifier;
        }

        /**
         * Sets the value of the codeListQualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeListQualifier(String value) {
            this.codeListQualifier = value;
        }

    }

}
