//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitsCoordinationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitsCoordinationResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayerIdentification" type="{http://www.ncpdp.org/schema/SCRIPT}PayerIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PayerName" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}ServiceTypeCoded" minOccurs="0"/>
 *         &lt;element name="CardholderID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element name="ResponsibleParty" type="{http://www.ncpdp.org/schema/SCRIPT}NameType" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="EffectiveDate" type="{http://www.ncpdp.org/schema/SCRIPT}DateType"/>
 *             &lt;element name="ExpirationDate" type="{http://www.ncpdp.org/schema/SCRIPT}DateType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Consent" type="{http://www.ncpdp.org/schema/SCRIPT}ConsentType" minOccurs="0"/>
 *         &lt;element name="PBMMemberID" type="{http://www.ncpdp.org/schema/SCRIPT}an..80" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitsCoordinationResponseType", propOrder = {
    "payerIdentification",
    "payerName",
    "serviceTypeCoded",
    "cardholderID",
    "responsibleParty",
    "groupID",
    "effectiveDate",
    "expirationDate",
    "consent",
    "pbmMemberID"
})
public class BenefitsCoordinationResponseType {

    @XmlElement(name = "PayerIdentification")
    protected List<PayerIDType> payerIdentification;
    @XmlElement(name = "PayerName")
    protected String payerName;
    @XmlElement(name = "ServiceTypeCoded")
    protected String serviceTypeCoded;
    @XmlElement(name = "CardholderID")
    protected String cardholderID;
    @XmlElement(name = "ResponsibleParty")
    protected NameType responsibleParty;
    @XmlElement(name = "GroupID")
    protected String groupID;
    @XmlElement(name = "EffectiveDate")
    protected DateType effectiveDate;
    @XmlElement(name = "ExpirationDate")
    protected DateType expirationDate;
    @XmlElement(name = "Consent")
    protected String consent;
    @XmlElement(name = "PBMMemberID")
    protected String pbmMemberID;

    /**
     * Gets the value of the payerIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payerIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayerIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayerIDType }
     * 
     * 
     */
    public List<PayerIDType> getPayerIdentification() {
        if (payerIdentification == null) {
            payerIdentification = new ArrayList<PayerIDType>();
        }
        return this.payerIdentification;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the serviceTypeCoded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceTypeCoded() {
        return serviceTypeCoded;
    }

    /**
     * Sets the value of the serviceTypeCoded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceTypeCoded(String value) {
        this.serviceTypeCoded = value;
    }

    /**
     * Gets the value of the cardholderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderID() {
        return cardholderID;
    }

    /**
     * Sets the value of the cardholderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderID(String value) {
        this.cardholderID = value;
    }

    /**
     * Gets the value of the responsibleParty property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getResponsibleParty() {
        return responsibleParty;
    }

    /**
     * Sets the value of the responsibleParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setResponsibleParty(NameType value) {
        this.responsibleParty = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setEffectiveDate(DateType value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setExpirationDate(DateType value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsent(String value) {
        this.consent = value;
    }

    /**
     * Gets the value of the pbmMemberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBMMemberID() {
        return pbmMemberID;
    }

    /**
     * Sets the value of the pbmMemberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBMMemberID(String value) {
        this.pbmMemberID = value;
    }

}
