//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitsCoordinationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitsCoordinationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayerIdentification" type="{http://www.ncpdp.org/schema/SCRIPT}PayerIDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PayerName" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element name="CardholderID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element name="CardHolderName" type="{http://www.ncpdp.org/schema/SCRIPT}NameType" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitsCoordinationType", propOrder = {
    "payerIdentification",
    "payerName",
    "cardholderID",
    "cardHolderName",
    "groupID"
})
public class BenefitsCoordinationType {

    @XmlElement(name = "PayerIdentification")
    protected List<PayerIDType> payerIdentification;
    @XmlElement(name = "PayerName")
    protected String payerName;
    @XmlElement(name = "CardholderID")
    protected String cardholderID;
    @XmlElement(name = "CardHolderName")
    protected NameType cardHolderName;
    @XmlElement(name = "GroupID")
    protected String groupID;

    /**
     * Gets the value of the payerIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payerIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayerIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PayerIDType }
     * 
     * 
     */
    public List<PayerIDType> getPayerIdentification() {
        if (payerIdentification == null) {
            payerIdentification = new ArrayList<PayerIDType>();
        }
        return this.payerIdentification;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the cardholderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderID() {
        return cardholderID;
    }

    /**
     * Sets the value of the cardholderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderID(String value) {
        this.cardholderID = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setCardHolderName(NameType value) {
        this.cardHolderName = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

}
