//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ncpdp.schema.script package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Quantity_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Quantity");
    private final static QName _DrugUseEvaluation_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DrugUseEvaluation");
    private final static QName _Description_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Description");
    private final static QName _PlaceLocationQualifier_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PlaceLocationQualifier");
    private final static QName _ItemDescriptionLong_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ItemDescriptionLong");
    private final static QName _Message_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Message");
    private final static QName _NeededNoLaterThanReason_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "NeededNoLaterThanReason");
    private final static QName _Allergy_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Allergy");
    private final static QName _DrugDescription_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DrugDescription");
    private final static QName _FacilityName_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "FacilityName");
    private final static QName _Note_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Note");
    private final static QName _Observation_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Observation");
    private final static QName _DateValidated_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DateValidated");
    private final static QName _Qualifier_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Qualifier");
    private final static QName _DoNotFill_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DoNotFill");
    private final static QName _Refills_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Refills");
    private final static QName _CommunicationNumbers_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "CommunicationNumbers");
    private final static QName _Specialty_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Specialty");
    private final static QName _ServiceTypeCoded_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ServiceTypeCoded");
    private final static QName _PatientRelationship_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PatientRelationship");
    private final static QName _DateOfBirth_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DateOfBirth");
    private final static QName _NeededNoLaterThan_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "NeededNoLaterThan");
    private final static QName _Address_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Address");
    private final static QName _Gender_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Gender");
    private final static QName _PriorAuthorizationStatus_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PriorAuthorizationStatus");
    private final static QName _DeliveredOnDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DeliveredOnDate");
    private final static QName _IDValue_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "IDValue");
    private final static QName _ItemNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ItemNumber");
    private final static QName _SoldDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "SoldDate");
    private final static QName _DrugCoverageStatusCode_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DrugCoverageStatusCode");
    private final static QName _DescriptionCode_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DescriptionCode");
    private final static QName _StructuredSIG_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "StructuredSIG");
    private final static QName _ClinicalInformationQualifier_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ClinicalInformationQualifier");
    private final static QName _DrugReferenceNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DrugReferenceNumber");
    private final static QName _LastFillDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "LastFillDate");
    private final static QName _EffectiveDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "EffectiveDate");
    private final static QName _ExpirationDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ExpirationDate");
    private final static QName _IDQualifier_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "IDQualifier");
    private final static QName _StoreName_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "StoreName");
    private final static QName _WrittenDate_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "WrittenDate");
    private final static QName _PeriodEnd_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PeriodEnd");
    private final static QName _Pharmacist_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Pharmacist");
    private final static QName _DaysSupply_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DaysSupply");
    private final static QName _DrugCoded_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DrugCoded");
    private final static QName _DiagnosisGeneral_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DiagnosisGeneral");
    private final static QName _Substitutions_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Substitutions");
    private final static QName _DeniedFillTypeFillReasonCode_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "FillReasonCode");
    private final static QName _DeniedFillTypeReferenceNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ReferenceNumber");
    private final static QName _OptionalProviderIDTypeCommercial_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "Commercial");
    private final static QName _OptionalProviderIDTypeDentistLicenseNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DentistLicenseNumber");
    private final static QName _OptionalProviderIDTypeMedicaidNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "MedicaidNumber");
    private final static QName _OptionalProviderIDTypeDEANumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "DEANumber");
    private final static QName _OptionalProviderIDTypeNPI_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "NPI");
    private final static QName _OptionalProviderIDTypeHIN_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "HIN");
    private final static QName _OptionalProviderIDTypeNAICCode_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "NAICCode");
    private final static QName _OptionalProviderIDTypeSecondaryCoverage_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "SecondaryCoverage");
    private final static QName _OptionalProviderIDTypePPONumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PPONumber");
    private final static QName _OptionalProviderIDTypePriorAuthorization_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PriorAuthorization");
    private final static QName _OptionalProviderIDTypePromotionNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PromotionNumber");
    private final static QName _OptionalProviderIDTypeProcessorIdentificationNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "ProcessorIdentificationNumber");
    private final static QName _OptionalProviderIDTypeIndividualPolicyNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "IndividualPolicyNumber");
    private final static QName _OptionalProviderIDTypeUPIN_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "UPIN");
    private final static QName _OptionalProviderIDTypeNCPDPID_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "NCPDPID");
    private final static QName _OptionalProviderIDTypePayerID_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PayerID");
    private final static QName _OptionalProviderIDTypeBINLocationNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "BINLocationNumber");
    private final static QName _OptionalProviderIDTypeMutuallyDefined_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "MutuallyDefined");
    private final static QName _OptionalProviderIDTypeMedicalRecordIdentificationNumberEHR_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "MedicalRecordIdentificationNumberEHR");
    private final static QName _OptionalProviderIDTypeFileID_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "FileID");
    private final static QName _OptionalProviderIDTypeSocialSecurity_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "SocialSecurity");
    private final static QName _OptionalProviderIDTypeFacilityID_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "FacilityID");
    private final static QName _OptionalProviderIDTypeStateLicenseNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "StateLicenseNumber");
    private final static QName _OptionalProviderIDTypePatientAccountNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "PatientAccountNumber");
    private final static QName _OptionalProviderIDTypeMedicareNumber_QNAME = new QName("http://www.ncpdp.org/schema/SCRIPT", "MedicareNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ncpdp.schema.script
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RefillRequest }
     * 
     */
    public RefillRequest createRefillRequest() {
        return new RefillRequest();
    }

    /**
     * Create an instance of {@link MandatoryPatientNameType }
     * 
     */
    public MandatoryPatientNameType createMandatoryPatientNameType() {
        return new MandatoryPatientNameType();
    }

    /**
     * Create an instance of {@link HistoryPrescriberType }
     * 
     */
    public HistoryPrescriberType createHistoryPrescriberType() {
        return new HistoryPrescriberType();
    }

    /**
     * Create an instance of {@link AllergyType.SeverityCoded }
     * 
     */
    public AllergyType.SeverityCoded createAllergyTypeSeverityCoded() {
        return new AllergyType.SeverityCoded();
    }

    /**
     * Create an instance of {@link RxChangeResponseMedicationType.Refills }
     * 
     */
    public RxChangeResponseMedicationType.Refills createRxChangeResponseMedicationTypeRefills() {
        return new RxChangeResponseMedicationType.Refills();
    }

    /**
     * Create an instance of {@link CommunicationNumbersType }
     * 
     */
    public CommunicationNumbersType createCommunicationNumbersType() {
        return new CommunicationNumbersType();
    }

    /**
     * Create an instance of {@link SIGType.Dose }
     * 
     */
    public SIGType.Dose createSIGTypeDose() {
        return new SIGType.Dose();
    }

    /**
     * Create an instance of {@link MandatoryNameType }
     * 
     */
    public MandatoryNameType createMandatoryNameType() {
        return new MandatoryNameType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientType();
    }

    /**
     * Create an instance of {@link CoAgentType }
     * 
     */
    public CoAgentType createCoAgentType() {
        return new CoAgentType();
    }

    /**
     * Create an instance of {@link BenefitsCoordinationType }
     * 
     */
    public BenefitsCoordinationType createBenefitsCoordinationType() {
        return new BenefitsCoordinationType();
    }

    /**
     * Create an instance of {@link Diagnosis }
     * 
     */
    public Diagnosis createDiagnosis() {
        return new Diagnosis();
    }

    /**
     * Create an instance of {@link DiagnosisType }
     * 
     */
    public DiagnosisType createDiagnosisType() {
        return new DiagnosisType();
    }

    /**
     * Create an instance of {@link UsernameTokenType }
     * 
     */
    public UsernameTokenType createUsernameTokenType() {
        return new UsernameTokenType();
    }

    /**
     * Create an instance of {@link MedicationHistoryRefillsType }
     * 
     */
    public MedicationHistoryRefillsType createMedicationHistoryRefillsType() {
        return new MedicationHistoryRefillsType();
    }

    /**
     * Create an instance of {@link OptionalProviderIDType }
     * 
     */
    public OptionalProviderIDType createOptionalProviderIDType() {
        return new OptionalProviderIDType();
    }

    /**
     * Create an instance of {@link ApprovedType }
     * 
     */
    public ApprovedType createApprovedType() {
        return new ApprovedType();
    }

    /**
     * Create an instance of {@link DiagnosisTypeGeneral }
     * 
     */
    public DiagnosisTypeGeneral createDiagnosisTypeGeneral() {
        return new DiagnosisTypeGeneral();
    }

    /**
     * Create an instance of {@link HeaderType.To }
     * 
     */
    public HeaderType.To createHeaderTypeTo() {
        return new HeaderType.To();
    }

    /**
     * Create an instance of {@link PrescriberRxFillType }
     * 
     */
    public PrescriberRxFillType createPrescriberRxFillType() {
        return new PrescriberRxFillType();
    }

    /**
     * Create an instance of {@link MandatoryPrescriberType }
     * 
     */
    public MandatoryPrescriberType createMandatoryPrescriberType() {
        return new MandatoryPrescriberType();
    }

    /**
     * Create an instance of {@link RxFill }
     * 
     */
    public RxFill createRxFill() {
        return new RxFill();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link CancelRequestType }
     * 
     */
    public CancelRequestType createCancelRequestType() {
        return new CancelRequestType();
    }

    /**
     * Create an instance of {@link RefillResponse }
     * 
     */
    public RefillResponse createRefillResponse() {
        return new RefillResponse();
    }

    /**
     * Create an instance of {@link SupervisorType }
     * 
     */
    public SupervisorType createSupervisorType() {
        return new SupervisorType();
    }

    /**
     * Create an instance of {@link RxChangePrescribedMedicationType }
     * 
     */
    public RxChangePrescribedMedicationType createRxChangePrescribedMedicationType() {
        return new RxChangePrescribedMedicationType();
    }

    /**
     * Create an instance of {@link NewRxPrescribedMedicationType }
     * 
     */
    public NewRxPrescribedMedicationType createNewRxPrescribedMedicationType() {
        return new NewRxPrescribedMedicationType();
    }

    /**
     * Create an instance of {@link Resupply }
     * 
     */
    public Resupply createResupply() {
        return new Resupply();
    }

    /**
     * Create an instance of {@link RefillResponseDispensedMedicationType.Refills }
     * 
     */
    public RefillResponseDispensedMedicationType.Refills createRefillResponseDispensedMedicationTypeRefills() {
        return new RefillResponseDispensedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link SIGType.RepeatingSIG }
     * 
     */
    public SIGType.RepeatingSIG createSIGTypeRepeatingSIG() {
        return new SIGType.RepeatingSIG();
    }

    /**
     * Create an instance of {@link CancelRx }
     * 
     */
    public CancelRx createCancelRx() {
        return new CancelRx();
    }

    /**
     * Create an instance of {@link PharmacyType }
     * 
     */
    public PharmacyType createPharmacyType() {
        return new PharmacyType();
    }

    /**
     * Create an instance of {@link PasswordChange }
     * 
     */
    public PasswordChange createPasswordChange() {
        return new PasswordChange();
    }

    /**
     * Create an instance of {@link FillStatusType }
     * 
     */
    public FillStatusType createFillStatusType() {
        return new FillStatusType();
    }

    /**
     * Create an instance of {@link OptionalPrescriberType }
     * 
     */
    public OptionalPrescriberType createOptionalPrescriberType() {
        return new OptionalPrescriberType();
    }

    /**
     * Create an instance of {@link IDOptionalType }
     * 
     */
    public IDOptionalType createIDOptionalType() {
        return new IDOptionalType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link RefillRequestDispensedMedicationType }
     * 
     */
    public RefillRequestDispensedMedicationType createRefillRequestDispensedMedicationType() {
        return new RefillRequestDispensedMedicationType();
    }

    /**
     * Create an instance of {@link HistoryResponsePatientType }
     * 
     */
    public HistoryResponsePatientType createHistoryResponsePatientType() {
        return new HistoryResponsePatientType();
    }

    /**
     * Create an instance of {@link MandatorySupervisorType }
     * 
     */
    public MandatorySupervisorType createMandatorySupervisorType() {
        return new MandatorySupervisorType();
    }

    /**
     * Create an instance of {@link RxChangeResponse }
     * 
     */
    public RxChangeResponse createRxChangeResponse() {
        return new RxChangeResponse();
    }

    /**
     * Create an instance of {@link Census }
     * 
     */
    public Census createCensus() {
        return new Census();
    }

    /**
     * Create an instance of {@link RefillRequestPrescribedMedicationType.Refills }
     * 
     */
    public RefillRequestPrescribedMedicationType.Refills createRefillRequestPrescribedMedicationTypeRefills() {
        return new RefillRequestPrescribedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link AllergyType.DrugProductCoded }
     * 
     */
    public AllergyType.DrugProductCoded createAllergyTypeDrugProductCoded() {
        return new AllergyType.DrugProductCoded();
    }

    /**
     * Create an instance of {@link DrugReferenceIDType }
     * 
     */
    public DrugReferenceIDType createDrugReferenceIDType() {
        return new DrugReferenceIDType();
    }

    /**
     * Create an instance of {@link Verify.VerifyStatus }
     * 
     */
    public Verify.VerifyStatus createVerifyVerifyStatus() {
        return new Verify.VerifyStatus();
    }

    /**
     * Create an instance of {@link MeasurementType }
     * 
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link RxChangeResponseMedicationType }
     * 
     */
    public RxChangeResponseMedicationType createRxChangeResponseMedicationType() {
        return new RxChangeResponseMedicationType();
    }

    /**
     * Create an instance of {@link HistorySourceType }
     * 
     */
    public HistorySourceType createHistorySourceType() {
        return new HistorySourceType();
    }

    /**
     * Create an instance of {@link ChangeResponseType }
     * 
     */
    public ChangeResponseType createChangeResponseType() {
        return new ChangeResponseType();
    }

    /**
     * Create an instance of {@link OptionalDateMedicationType }
     * 
     */
    public OptionalDateMedicationType createOptionalDateMedicationType() {
        return new OptionalDateMedicationType();
    }

    /**
     * Create an instance of {@link NewRx }
     * 
     */
    public NewRx createNewRx() {
        return new NewRx();
    }

    /**
     * Create an instance of {@link CommunicationType }
     * 
     */
    public CommunicationType createCommunicationType() {
        return new CommunicationType();
    }

    /**
     * Create an instance of {@link RxFillMedicationType }
     * 
     */
    public RxFillMedicationType createRxFillMedicationType() {
        return new RxFillMedicationType();
    }

    /**
     * Create an instance of {@link CensusBenefitsCoordinationType }
     * 
     */
    public CensusBenefitsCoordinationType createCensusBenefitsCoordinationType() {
        return new CensusBenefitsCoordinationType();
    }

    /**
     * Create an instance of {@link MandatoryProviderIDType }
     * 
     */
    public MandatoryProviderIDType createMandatoryProviderIDType() {
        return new MandatoryProviderIDType();
    }

    /**
     * Create an instance of {@link DeniedType }
     * 
     */
    public DeniedType createDeniedType() {
        return new DeniedType();
    }

    /**
     * Create an instance of {@link DeniedNewRxToFollowType }
     * 
     */
    public DeniedNewRxToFollowType createDeniedNewRxToFollowType() {
        return new DeniedNewRxToFollowType();
    }

    /**
     * Create an instance of {@link SupervisorTypeRefillRequest }
     * 
     */
    public SupervisorTypeRefillRequest createSupervisorTypeRefillRequest() {
        return new SupervisorTypeRefillRequest();
    }

    /**
     * Create an instance of {@link SupervisorRxFillType }
     * 
     */
    public SupervisorRxFillType createSupervisorRxFillType() {
        return new SupervisorRxFillType();
    }

    /**
     * Create an instance of {@link RefillRequestDispensedMedicationType.Refills }
     * 
     */
    public RefillRequestDispensedMedicationType.Refills createRefillRequestDispensedMedicationTypeRefills() {
        return new RefillRequestDispensedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link SIGType.DoseCalculation }
     * 
     */
    public SIGType.DoseCalculation createSIGTypeDoseCalculation() {
        return new SIGType.DoseCalculation();
    }

    /**
     * Create an instance of {@link BodyType }
     * 
     */
    public BodyType createBodyType() {
        return new BodyType();
    }

    /**
     * Create an instance of {@link FaciltyType }
     * 
     */
    public FaciltyType createFaciltyType() {
        return new FaciltyType();
    }

    /**
     * Create an instance of {@link AllergyType.ReactionCoded }
     * 
     */
    public AllergyType.ReactionCoded createAllergyTypeReactionCoded() {
        return new AllergyType.ReactionCoded();
    }

    /**
     * Create an instance of {@link DiagnosisTypeGeneral.ProblemNameCoded }
     * 
     */
    public DiagnosisTypeGeneral.ProblemNameCoded createDiagnosisTypeGeneralProblemNameCoded() {
        return new DiagnosisTypeGeneral.ProblemNameCoded();
    }

    /**
     * Create an instance of {@link ShortRequestType }
     * 
     */
    public ShortRequestType createShortRequestType() {
        return new ShortRequestType();
    }

    /**
     * Create an instance of {@link BenefitsCoordinationResponseType }
     * 
     */
    public BenefitsCoordinationResponseType createBenefitsCoordinationResponseType() {
        return new BenefitsCoordinationResponseType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link MandatoryFaciltyType }
     * 
     */
    public MandatoryFaciltyType createMandatoryFaciltyType() {
        return new MandatoryFaciltyType();
    }

    /**
     * Create an instance of {@link ResupplyMedicationType }
     * 
     */
    public ResupplyMedicationType createResupplyMedicationType() {
        return new ResupplyMedicationType();
    }

    /**
     * Create an instance of {@link MandatoryPharmacyType }
     * 
     */
    public MandatoryPharmacyType createMandatoryPharmacyType() {
        return new MandatoryPharmacyType();
    }

    /**
     * Create an instance of {@link PasswordRequestType }
     * 
     */
    public PasswordRequestType createPasswordRequestType() {
        return new PasswordRequestType();
    }

    /**
     * Create an instance of {@link SIGType.Timing }
     * 
     */
    public SIGType.Timing createSIGTypeTiming() {
        return new SIGType.Timing();
    }

    /**
     * Create an instance of {@link SecurityType }
     * 
     */
    public SecurityType createSecurityType() {
        return new SecurityType();
    }

    /**
     * Create an instance of {@link RxChangeRequest }
     * 
     */
    public RxChangeRequest createRxChangeRequest() {
        return new RxChangeRequest();
    }

    /**
     * Create an instance of {@link RefillRequestPrescribedMedicationType }
     * 
     */
    public RefillRequestPrescribedMedicationType createRefillRequestPrescribedMedicationType() {
        return new RefillRequestPrescribedMedicationType();
    }

    /**
     * Create an instance of {@link RxChangePrescribedMedicationType.Refills }
     * 
     */
    public RxChangePrescribedMedicationType.Refills createRxChangePrescribedMedicationTypeRefills() {
        return new RxChangePrescribedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link RxChangeDispensedMedicationType.Refills }
     * 
     */
    public RxChangeDispensedMedicationType.Refills createRxChangeDispensedMedicationTypeRefills() {
        return new RxChangeDispensedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link PasswordType }
     * 
     */
    public PasswordType createPasswordType() {
        return new PasswordType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link PatientLocation }
     * 
     */
    public PatientLocation createPatientLocation() {
        return new PatientLocation();
    }

    /**
     * Create an instance of {@link RxHistoryResponse }
     * 
     */
    public RxHistoryResponse createRxHistoryResponse() {
        return new RxHistoryResponse();
    }

    /**
     * Create an instance of {@link IDMandatoryType }
     * 
     */
    public IDMandatoryType createIDMandatoryType() {
        return new IDMandatoryType();
    }

    /**
     * Create an instance of {@link SIGType.MaximumDoseRestriction }
     * 
     */
    public SIGType.MaximumDoseRestriction createSIGTypeMaximumDoseRestriction() {
        return new SIGType.MaximumDoseRestriction();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link RefillsType }
     * 
     */
    public RefillsType createRefillsType() {
        return new RefillsType();
    }

    /**
     * Create an instance of {@link MandatoryAddressType }
     * 
     */
    public MandatoryAddressType createMandatoryAddressType() {
        return new MandatoryAddressType();
    }

    /**
     * Create an instance of {@link SIGType.RouteofAdministration }
     * 
     */
    public SIGType.RouteofAdministration createSIGTypeRouteofAdministration() {
        return new SIGType.RouteofAdministration();
    }

    /**
     * Create an instance of {@link ObservationType }
     * 
     */
    public ObservationType createObservationType() {
        return new ObservationType();
    }

    /**
     * Create an instance of {@link HistoryDispensedMedicationType }
     * 
     */
    public HistoryDispensedMedicationType createHistoryDispensedMedicationType() {
        return new HistoryDispensedMedicationType();
    }

    /**
     * Create an instance of {@link DispensedMedicationType }
     * 
     */
    public DispensedMedicationType createDispensedMedicationType() {
        return new DispensedMedicationType();
    }

    /**
     * Create an instance of {@link NewRxPrescribedMedicationType.Refills }
     * 
     */
    public NewRxPrescribedMedicationType.Refills createNewRxPrescribedMedicationTypeRefills() {
        return new NewRxPrescribedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link GetMessage }
     * 
     */
    public GetMessage createGetMessage() {
        return new GetMessage();
    }

    /**
     * Create an instance of {@link HeaderType.From }
     * 
     */
    public HeaderType.From createHeaderTypeFrom() {
        return new HeaderType.From();
    }

    /**
     * Create an instance of {@link PriorAuthorizationType }
     * 
     */
    public PriorAuthorizationType createPriorAuthorizationType() {
        return new PriorAuthorizationType();
    }

    /**
     * Create an instance of {@link HistoryResponseType }
     * 
     */
    public HistoryResponseType createHistoryResponseType() {
        return new HistoryResponseType();
    }

    /**
     * Create an instance of {@link SIGType.SiteofAdministration }
     * 
     */
    public SIGType.SiteofAdministration createSIGTypeSiteofAdministration() {
        return new SIGType.SiteofAdministration();
    }

    /**
     * Create an instance of {@link DeniedFillType }
     * 
     */
    public DeniedFillType createDeniedFillType() {
        return new DeniedFillType();
    }

    /**
     * Create an instance of {@link RxFillDispensedMedicationType }
     * 
     */
    public RxFillDispensedMedicationType createRxFillDispensedMedicationType() {
        return new RxFillDispensedMedicationType();
    }

    /**
     * Create an instance of {@link RxChangeDispensedMedicationType }
     * 
     */
    public RxChangeDispensedMedicationType createRxChangeDispensedMedicationType() {
        return new RxChangeDispensedMedicationType();
    }

    /**
     * Create an instance of {@link NewRxRequestType }
     * 
     */
    public NewRxRequestType createNewRxRequestType() {
        return new NewRxRequestType();
    }

    /**
     * Create an instance of {@link CensusRequestType }
     * 
     */
    public CensusRequestType createCensusRequestType() {
        return new CensusRequestType();
    }

    /**
     * Create an instance of {@link RefillResponseDispensedMedicationType }
     * 
     */
    public RefillResponseDispensedMedicationType createRefillResponseDispensedMedicationType() {
        return new RefillResponseDispensedMedicationType();
    }

    /**
     * Create an instance of {@link HistoryRequestPatientType }
     * 
     */
    public HistoryRequestPatientType createHistoryRequestPatientType() {
        return new HistoryRequestPatientType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link MedicationType }
     * 
     */
    public MedicationType createMedicationType() {
        return new MedicationType();
    }

    /**
     * Create an instance of {@link SIGType.Indication }
     * 
     */
    public SIGType.Indication createSIGTypeIndication() {
        return new SIGType.Indication();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link RefillResponsePrescribedMedicationType }
     * 
     */
    public RefillResponsePrescribedMedicationType createRefillResponsePrescribedMedicationType() {
        return new RefillResponsePrescribedMedicationType();
    }

    /**
     * Create an instance of {@link RxHistoryRequest }
     * 
     */
    public RxHistoryRequest createRxHistoryRequest() {
        return new RxHistoryRequest();
    }

    /**
     * Create an instance of {@link MailboxType }
     * 
     */
    public MailboxType createMailboxType() {
        return new MailboxType();
    }

    /**
     * Create an instance of {@link SIGType.FreeText }
     * 
     */
    public SIGType.FreeText createSIGTypeFreeText() {
        return new SIGType.FreeText();
    }

    /**
     * Create an instance of {@link PatientIDType }
     * 
     */
    public PatientIDType createPatientIDType() {
        return new PatientIDType();
    }

    /**
     * Create an instance of {@link ResupplyMedicationType.Refills }
     * 
     */
    public ResupplyMedicationType.Refills createResupplyMedicationTypeRefills() {
        return new ResupplyMedicationType.Refills();
    }

    /**
     * Create an instance of {@link PayerIDType }
     * 
     */
    public PayerIDType createPayerIDType() {
        return new PayerIDType();
    }

    /**
     * Create an instance of {@link CancelRxResponse }
     * 
     */
    public CancelRxResponse createCancelRxResponse() {
        return new CancelRxResponse();
    }

    /**
     * Create an instance of {@link HistorySourceType.Source }
     * 
     */
    public HistorySourceType.Source createHistorySourceTypeSource() {
        return new HistorySourceType.Source();
    }

    /**
     * Create an instance of {@link HistoryPrescribedMedicationType }
     * 
     */
    public HistoryPrescribedMedicationType createHistoryPrescribedMedicationType() {
        return new HistoryPrescribedMedicationType();
    }

    /**
     * Create an instance of {@link ApprovedWithChangesType }
     * 
     */
    public ApprovedWithChangesType createApprovedWithChangesType() {
        return new ApprovedWithChangesType();
    }

    /**
     * Create an instance of {@link AllergyType.AdverseEvent }
     * 
     */
    public AllergyType.AdverseEvent createAllergyTypeAdverseEvent() {
        return new AllergyType.AdverseEvent();
    }

    /**
     * Create an instance of {@link SecurityIdentificationType }
     * 
     */
    public SecurityIdentificationType createSecurityIdentificationType() {
        return new SecurityIdentificationType();
    }

    /**
     * Create an instance of {@link DiagnosisTypeGeneral.ProblemType }
     * 
     */
    public DiagnosisTypeGeneral.ProblemType createDiagnosisTypeGeneralProblemType() {
        return new DiagnosisTypeGeneral.ProblemType();
    }

    /**
     * Create an instance of {@link SIGType.Stop }
     * 
     */
    public SIGType.Stop createSIGTypeStop() {
        return new SIGType.Stop();
    }

    /**
     * Create an instance of {@link SIGType.Duration }
     * 
     */
    public SIGType.Duration createSIGTypeDuration() {
        return new SIGType.Duration();
    }

    /**
     * Create an instance of {@link PrescribedMedicationType }
     * 
     */
    public PrescribedMedicationType createPrescribedMedicationType() {
        return new PrescribedMedicationType();
    }

    /**
     * Create an instance of {@link OptionalPharmacyType }
     * 
     */
    public OptionalPharmacyType createOptionalPharmacyType() {
        return new OptionalPharmacyType();
    }

    /**
     * Create an instance of {@link BenefitsCoordinationRequestType }
     * 
     */
    public BenefitsCoordinationRequestType createBenefitsCoordinationRequestType() {
        return new BenefitsCoordinationRequestType();
    }

    /**
     * Create an instance of {@link DrugUseEvaluationType }
     * 
     */
    public DrugUseEvaluationType createDrugUseEvaluationType() {
        return new DrugUseEvaluationType();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link RefillResponsePrescribedMedicationType.Refills }
     * 
     */
    public RefillResponsePrescribedMedicationType.Refills createRefillResponsePrescribedMedicationTypeRefills() {
        return new RefillResponsePrescribedMedicationType.Refills();
    }

    /**
     * Create an instance of {@link PrimaryDiagnosisType }
     * 
     */
    public PrimaryDiagnosisType createPrimaryDiagnosisType() {
        return new PrimaryDiagnosisType();
    }

    /**
     * Create an instance of {@link SIGType.CodeSystem }
     * 
     */
    public SIGType.CodeSystem createSIGTypeCodeSystem() {
        return new SIGType.CodeSystem();
    }

    /**
     * Create an instance of {@link SIGType }
     * 
     */
    public SIGType createSIGType() {
        return new SIGType();
    }

    /**
     * Create an instance of {@link SIGType.Vehicle }
     * 
     */
    public SIGType.Vehicle createSIGTypeVehicle() {
        return new SIGType.Vehicle();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link AllergyType }
     * 
     */
    public AllergyType createAllergyType() {
        return new AllergyType();
    }

    /**
     * Create an instance of {@link PrescriberType }
     * 
     */
    public PrescriberType createPrescriberType() {
        return new PrescriberType();
    }

    /**
     * Create an instance of {@link MandatoryAddressPharmacyType }
     * 
     */
    public MandatoryAddressPharmacyType createMandatoryAddressPharmacyType() {
        return new MandatoryAddressPharmacyType();
    }

    /**
     * Create an instance of {@link PrescriberTypeRefillRequest }
     * 
     */
    public PrescriberTypeRefillRequest createPrescriberTypeRefillRequest() {
        return new PrescriberTypeRefillRequest();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link Verify }
     * 
     */
    public Verify createVerify() {
        return new Verify();
    }

    /**
     * Create an instance of {@link DrugCodedType }
     * 
     */
    public DrugCodedType createDrugCodedType() {
        return new DrugCodedType();
    }

    /**
     * Create an instance of {@link TimeZone }
     * 
     */
    public TimeZone createTimeZone() {
        return new TimeZone();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Quantity")
    public JAXBElement<QuantityType> createQuantity(QuantityType value) {
        return new JAXBElement<QuantityType>(_Quantity_QNAME, QuantityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugUseEvaluationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DrugUseEvaluation")
    public JAXBElement<DrugUseEvaluationType> createDrugUseEvaluation(DrugUseEvaluationType value) {
        return new JAXBElement<DrugUseEvaluationType>(_DrugUseEvaluation_QNAME, DrugUseEvaluationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PlaceLocationQualifier")
    public JAXBElement<String> createPlaceLocationQualifier(String value) {
        return new JAXBElement<String>(_PlaceLocationQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ItemDescriptionLong")
    public JAXBElement<String> createItemDescriptionLong(String value) {
        return new JAXBElement<String>(_ItemDescriptionLong_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Message")
    public JAXBElement<MessageType> createMessage(MessageType value) {
        return new JAXBElement<MessageType>(_Message_QNAME, MessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NeededNoLaterThanReason")
    public JAXBElement<String> createNeededNoLaterThanReason(String value) {
        return new JAXBElement<String>(_NeededNoLaterThanReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllergyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Allergy")
    public JAXBElement<AllergyType> createAllergy(AllergyType value) {
        return new JAXBElement<AllergyType>(_Allergy_QNAME, AllergyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DrugDescription")
    public JAXBElement<String> createDrugDescription(String value) {
        return new JAXBElement<String>(_DrugDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FacilityName")
    public JAXBElement<String> createFacilityName(String value) {
        return new JAXBElement<String>(_FacilityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Note")
    public JAXBElement<String> createNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObservationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Observation")
    public JAXBElement<ObservationType> createObservation(ObservationType value) {
        return new JAXBElement<ObservationType>(_Observation_QNAME, ObservationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DateValidated")
    public JAXBElement<DateType> createDateValidated(DateType value) {
        return new JAXBElement<DateType>(_DateValidated_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Qualifier")
    public JAXBElement<String> createQualifier(String value) {
        return new JAXBElement<String>(_Qualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DoNotFill")
    public JAXBElement<String> createDoNotFill(String value) {
        return new JAXBElement<String>(_DoNotFill_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefillsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Refills")
    public JAXBElement<RefillsType> createRefills(RefillsType value) {
        return new JAXBElement<RefillsType>(_Refills_QNAME, RefillsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationNumbersType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "CommunicationNumbers")
    public JAXBElement<CommunicationNumbersType> createCommunicationNumbers(CommunicationNumbersType value) {
        return new JAXBElement<CommunicationNumbersType>(_CommunicationNumbers_QNAME, CommunicationNumbersType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Specialty")
    public JAXBElement<String> createSpecialty(String value) {
        return new JAXBElement<String>(_Specialty_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ServiceTypeCoded")
    public JAXBElement<String> createServiceTypeCoded(String value) {
        return new JAXBElement<String>(_ServiceTypeCoded_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PatientRelationship")
    public JAXBElement<String> createPatientRelationship(String value) {
        return new JAXBElement<String>(_PatientRelationship_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DateOfBirth")
    public JAXBElement<DateType> createDateOfBirth(DateType value) {
        return new JAXBElement<DateType>(_DateOfBirth_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NeededNoLaterThan")
    public JAXBElement<XMLGregorianCalendar> createNeededNoLaterThan(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NeededNoLaterThan_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Address")
    public JAXBElement<AddressType> createAddress(AddressType value) {
        return new JAXBElement<AddressType>(_Address_QNAME, AddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PriorAuthorizationStatus")
    public JAXBElement<String> createPriorAuthorizationStatus(String value) {
        return new JAXBElement<String>(_PriorAuthorizationStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DeliveredOnDate")
    public JAXBElement<DateType> createDeliveredOnDate(DateType value) {
        return new JAXBElement<DateType>(_DeliveredOnDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "IDValue")
    public JAXBElement<String> createIDValue(String value) {
        return new JAXBElement<String>(_IDValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ItemNumber")
    public JAXBElement<String> createItemNumber(String value) {
        return new JAXBElement<String>(_ItemNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SoldDate")
    public JAXBElement<DateType> createSoldDate(DateType value) {
        return new JAXBElement<DateType>(_SoldDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DrugCoverageStatusCode")
    public JAXBElement<String> createDrugCoverageStatusCode(String value) {
        return new JAXBElement<String>(_DrugCoverageStatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DescriptionCode")
    public JAXBElement<String> createDescriptionCode(String value) {
        return new JAXBElement<String>(_DescriptionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SIGType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "StructuredSIG")
    public JAXBElement<SIGType> createStructuredSIG(SIGType value) {
        return new JAXBElement<SIGType>(_StructuredSIG_QNAME, SIGType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ClinicalInformationQualifier")
    public JAXBElement<String> createClinicalInformationQualifier(String value) {
        return new JAXBElement<String>(_ClinicalInformationQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugReferenceIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DrugReferenceNumber")
    public JAXBElement<DrugReferenceIDType> createDrugReferenceNumber(DrugReferenceIDType value) {
        return new JAXBElement<DrugReferenceIDType>(_DrugReferenceNumber_QNAME, DrugReferenceIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "LastFillDate")
    public JAXBElement<DateType> createLastFillDate(DateType value) {
        return new JAXBElement<DateType>(_LastFillDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "EffectiveDate")
    public JAXBElement<DateType> createEffectiveDate(DateType value) {
        return new JAXBElement<DateType>(_EffectiveDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ExpirationDate")
    public JAXBElement<DateType> createExpirationDate(DateType value) {
        return new JAXBElement<DateType>(_ExpirationDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "IDQualifier")
    public JAXBElement<String> createIDQualifier(String value) {
        return new JAXBElement<String>(_IDQualifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "StoreName")
    public JAXBElement<String> createStoreName(String value) {
        return new JAXBElement<String>(_StoreName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "WrittenDate")
    public JAXBElement<DateType> createWrittenDate(DateType value) {
        return new JAXBElement<DateType>(_WrittenDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PeriodEnd")
    public JAXBElement<DateType> createPeriodEnd(DateType value) {
        return new JAXBElement<DateType>(_PeriodEnd_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Pharmacist")
    public JAXBElement<NameType> createPharmacist(NameType value) {
        return new JAXBElement<NameType>(_Pharmacist_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DaysSupply")
    public JAXBElement<String> createDaysSupply(String value) {
        return new JAXBElement<String>(_DaysSupply_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrugCodedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DrugCoded")
    public JAXBElement<DrugCodedType> createDrugCoded(DrugCodedType value) {
        return new JAXBElement<DrugCodedType>(_DrugCoded_QNAME, DrugCodedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiagnosisTypeGeneral }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DiagnosisGeneral")
    public JAXBElement<DiagnosisTypeGeneral> createDiagnosisGeneral(DiagnosisTypeGeneral value) {
        return new JAXBElement<DiagnosisTypeGeneral>(_DiagnosisGeneral_QNAME, DiagnosisTypeGeneral.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Substitutions")
    public JAXBElement<String> createSubstitutions(String value) {
        return new JAXBElement<String>(_Substitutions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FillReasonCode", scope = DeniedFillType.class)
    public JAXBElement<String> createDeniedFillTypeFillReasonCode(String value) {
        return new JAXBElement<String>(_DeniedFillTypeFillReasonCode_QNAME, String.class, DeniedFillType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ReferenceNumber", scope = DeniedFillType.class)
    public JAXBElement<String> createDeniedFillTypeReferenceNumber(String value) {
        return new JAXBElement<String>(_DeniedFillTypeReferenceNumber_QNAME, String.class, DeniedFillType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Note", scope = DeniedFillType.class)
    public JAXBElement<String> createDeniedFillTypeNote(String value) {
        return new JAXBElement<String>(_Note_QNAME, String.class, DeniedFillType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Commercial", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeCommercial(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeCommercial_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DentistLicenseNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeDentistLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDentistLicenseNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicaidNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeMedicaidNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicaidNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DEANumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeDEANumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDEANumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NPI", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeNPI(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNPI_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "HIN", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeHIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeHIN_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NAICCode", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeNAICCode(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNAICCode_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SecondaryCoverage", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeSecondaryCoverage(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSecondaryCoverage_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PPONumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypePPONumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePPONumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PriorAuthorization", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypePriorAuthorization(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePriorAuthorization_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PromotionNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypePromotionNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePromotionNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ProcessorIdentificationNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeProcessorIdentificationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeProcessorIdentificationNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "IndividualPolicyNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeIndividualPolicyNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeIndividualPolicyNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "UPIN", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeUPIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeUPIN_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NCPDPID", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeNCPDPID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNCPDPID_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PayerID", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypePayerID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePayerID_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "BINLocationNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeBINLocationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeBINLocationNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MutuallyDefined", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeMutuallyDefined(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMutuallyDefined_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicalRecordIdentificationNumberEHR", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeMedicalRecordIdentificationNumberEHR(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicalRecordIdentificationNumberEHR_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FileID", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeFileID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFileID_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SocialSecurity", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeSocialSecurity(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSocialSecurity_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FacilityID", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeFacilityID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFacilityID_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "StateLicenseNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeStateLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeStateLicenseNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PatientAccountNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypePatientAccountNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePatientAccountNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicareNumber", scope = OptionalProviderIDType.class)
    public JAXBElement<String> createOptionalProviderIDTypeMedicareNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicareNumber_QNAME, String.class, OptionalProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Commercial", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeCommercial(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeCommercial_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicaidNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeMedicaidNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicaidNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DentistLicenseNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeDentistLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDentistLicenseNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DEANumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeDEANumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDEANumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NPI", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeNPI(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNPI_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "HIN", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeHIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeHIN_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NAICCode", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeNAICCode(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNAICCode_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SecondaryCoverage", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeSecondaryCoverage(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSecondaryCoverage_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PPONumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypePPONumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePPONumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PromotionNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypePromotionNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePromotionNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PriorAuthorization", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypePriorAuthorization(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePriorAuthorization_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ProcessorIdentificationNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeProcessorIdentificationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeProcessorIdentificationNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "IndividualPolicyNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeIndividualPolicyNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeIndividualPolicyNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NCPDPID", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeNCPDPID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNCPDPID_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PayerID", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypePayerID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePayerID_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "UPIN", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeUPIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeUPIN_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "BINLocationNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeBINLocationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeBINLocationNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MutuallyDefined", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeMutuallyDefined(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMutuallyDefined_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicalRecordIdentificationNumberEHR", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeMedicalRecordIdentificationNumberEHR(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicalRecordIdentificationNumberEHR_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FileID", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeFileID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFileID_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SocialSecurity", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeSocialSecurity(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSocialSecurity_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FacilityID", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeFacilityID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFacilityID_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "StateLicenseNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeStateLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeStateLicenseNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PatientAccountNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypePatientAccountNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePatientAccountNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicareNumber", scope = PatientIDType.class)
    public JAXBElement<String> createPatientIDTypeMedicareNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicareNumber_QNAME, String.class, PatientIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "Commercial", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeCommercial(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeCommercial_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicaidNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeMedicaidNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicaidNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DentistLicenseNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeDentistLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDentistLicenseNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "DEANumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeDEANumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeDEANumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NPI", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeNPI(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNPI_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "HIN", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeHIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeHIN_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NAICCode", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeNAICCode(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNAICCode_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SecondaryCoverage", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeSecondaryCoverage(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSecondaryCoverage_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PPONumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypePPONumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePPONumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PriorAuthorization", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypePriorAuthorization(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePriorAuthorization_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PromotionNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypePromotionNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePromotionNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "ProcessorIdentificationNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeProcessorIdentificationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeProcessorIdentificationNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "IndividualPolicyNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeIndividualPolicyNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeIndividualPolicyNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "NCPDPID", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeNCPDPID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeNCPDPID_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PayerID", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypePayerID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePayerID_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "UPIN", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeUPIN(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeUPIN_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "BINLocationNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeBINLocationNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeBINLocationNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MutuallyDefined", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeMutuallyDefined(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMutuallyDefined_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicalRecordIdentificationNumberEHR", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeMedicalRecordIdentificationNumberEHR(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicalRecordIdentificationNumberEHR_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FileID", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeFileID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFileID_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "SocialSecurity", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeSocialSecurity(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeSocialSecurity_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "FacilityID", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeFacilityID(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeFacilityID_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "StateLicenseNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeStateLicenseNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeStateLicenseNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "PatientAccountNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypePatientAccountNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypePatientAccountNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ncpdp.org/schema/SCRIPT", name = "MedicareNumber", scope = MandatoryProviderIDType.class)
    public JAXBElement<String> createMandatoryProviderIDTypeMedicareNumber(String value) {
        return new JAXBElement<String>(_OptionalProviderIDTypeMedicareNumber_QNAME, String.class, MandatoryProviderIDType.class, value);
    }

}
