//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PayerIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayerIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="NCPDPID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="FileID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="StateLicenseNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicareNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicaidNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="DentistLicenseNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="UPIN" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="FacilityID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PPONumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PayerID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="ProcessorIdentificationNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="BINLocationNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="Commercial" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicalRecordIdentificationNumberEHR" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PatientAccountNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="DEANumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="HIN" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="IndividualPolicyNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="SecondaryCoverage" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="NAICCode" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PromotionNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="SocialSecurity" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="NPI" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PriorAuthorization" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MutuallyDefined" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayerIDType", propOrder = {
    "ncpdpid",
    "fileID",
    "stateLicenseNumber",
    "medicareNumber",
    "medicaidNumber",
    "dentistLicenseNumber",
    "upin",
    "facilityID",
    "ppoNumber",
    "payerID",
    "processorIdentificationNumber",
    "binLocationNumber",
    "commercial",
    "medicalRecordIdentificationNumberEHR",
    "patientAccountNumber",
    "deaNumber",
    "hin",
    "individualPolicyNumber",
    "secondaryCoverage",
    "naicCode",
    "promotionNumber",
    "socialSecurity",
    "npi",
    "priorAuthorization",
    "mutuallyDefined"
})
public class PayerIDType {

    @XmlElement(name = "NCPDPID")
    protected String ncpdpid;
    @XmlElement(name = "FileID")
    protected String fileID;
    @XmlElement(name = "StateLicenseNumber")
    protected String stateLicenseNumber;
    @XmlElement(name = "MedicareNumber")
    protected String medicareNumber;
    @XmlElement(name = "MedicaidNumber")
    protected String medicaidNumber;
    @XmlElement(name = "DentistLicenseNumber")
    protected String dentistLicenseNumber;
    @XmlElement(name = "UPIN")
    protected String upin;
    @XmlElement(name = "FacilityID")
    protected String facilityID;
    @XmlElement(name = "PPONumber")
    protected String ppoNumber;
    @XmlElement(name = "PayerID")
    protected String payerID;
    @XmlElement(name = "ProcessorIdentificationNumber")
    protected String processorIdentificationNumber;
    @XmlElement(name = "BINLocationNumber")
    protected String binLocationNumber;
    @XmlElement(name = "Commercial")
    protected String commercial;
    @XmlElement(name = "MedicalRecordIdentificationNumberEHR")
    protected String medicalRecordIdentificationNumberEHR;
    @XmlElement(name = "PatientAccountNumber")
    protected String patientAccountNumber;
    @XmlElement(name = "DEANumber")
    protected String deaNumber;
    @XmlElement(name = "HIN")
    protected String hin;
    @XmlElement(name = "IndividualPolicyNumber")
    protected String individualPolicyNumber;
    @XmlElement(name = "SecondaryCoverage")
    protected String secondaryCoverage;
    @XmlElement(name = "NAICCode")
    protected String naicCode;
    @XmlElement(name = "PromotionNumber")
    protected String promotionNumber;
    @XmlElement(name = "SocialSecurity")
    protected String socialSecurity;
    @XmlElement(name = "NPI")
    protected String npi;
    @XmlElement(name = "PriorAuthorization")
    protected String priorAuthorization;
    @XmlElement(name = "MutuallyDefined")
    protected String mutuallyDefined;

    /**
     * Gets the value of the ncpdpid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCPDPID() {
        return ncpdpid;
    }

    /**
     * Sets the value of the ncpdpid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCPDPID(String value) {
        this.ncpdpid = value;
    }

    /**
     * Gets the value of the fileID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileID() {
        return fileID;
    }

    /**
     * Sets the value of the fileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileID(String value) {
        this.fileID = value;
    }

    /**
     * Gets the value of the stateLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateLicenseNumber() {
        return stateLicenseNumber;
    }

    /**
     * Sets the value of the stateLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateLicenseNumber(String value) {
        this.stateLicenseNumber = value;
    }

    /**
     * Gets the value of the medicareNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicareNumber() {
        return medicareNumber;
    }

    /**
     * Sets the value of the medicareNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicareNumber(String value) {
        this.medicareNumber = value;
    }

    /**
     * Gets the value of the medicaidNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicaidNumber() {
        return medicaidNumber;
    }

    /**
     * Sets the value of the medicaidNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicaidNumber(String value) {
        this.medicaidNumber = value;
    }

    /**
     * Gets the value of the dentistLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDentistLicenseNumber() {
        return dentistLicenseNumber;
    }

    /**
     * Sets the value of the dentistLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDentistLicenseNumber(String value) {
        this.dentistLicenseNumber = value;
    }

    /**
     * Gets the value of the upin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPIN() {
        return upin;
    }

    /**
     * Sets the value of the upin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPIN(String value) {
        this.upin = value;
    }

    /**
     * Gets the value of the facilityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityID() {
        return facilityID;
    }

    /**
     * Sets the value of the facilityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityID(String value) {
        this.facilityID = value;
    }

    /**
     * Gets the value of the ppoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPPONumber() {
        return ppoNumber;
    }

    /**
     * Sets the value of the ppoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPPONumber(String value) {
        this.ppoNumber = value;
    }

    /**
     * Gets the value of the payerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerID() {
        return payerID;
    }

    /**
     * Sets the value of the payerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerID(String value) {
        this.payerID = value;
    }

    /**
     * Gets the value of the processorIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessorIdentificationNumber() {
        return processorIdentificationNumber;
    }

    /**
     * Sets the value of the processorIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessorIdentificationNumber(String value) {
        this.processorIdentificationNumber = value;
    }

    /**
     * Gets the value of the binLocationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBINLocationNumber() {
        return binLocationNumber;
    }

    /**
     * Sets the value of the binLocationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBINLocationNumber(String value) {
        this.binLocationNumber = value;
    }

    /**
     * Gets the value of the commercial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercial() {
        return commercial;
    }

    /**
     * Sets the value of the commercial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercial(String value) {
        this.commercial = value;
    }

    /**
     * Gets the value of the medicalRecordIdentificationNumberEHR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalRecordIdentificationNumberEHR() {
        return medicalRecordIdentificationNumberEHR;
    }

    /**
     * Sets the value of the medicalRecordIdentificationNumberEHR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalRecordIdentificationNumberEHR(String value) {
        this.medicalRecordIdentificationNumberEHR = value;
    }

    /**
     * Gets the value of the patientAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientAccountNumber() {
        return patientAccountNumber;
    }

    /**
     * Sets the value of the patientAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientAccountNumber(String value) {
        this.patientAccountNumber = value;
    }

    /**
     * Gets the value of the deaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEANumber() {
        return deaNumber;
    }

    /**
     * Sets the value of the deaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEANumber(String value) {
        this.deaNumber = value;
    }

    /**
     * Gets the value of the hin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHIN() {
        return hin;
    }

    /**
     * Sets the value of the hin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHIN(String value) {
        this.hin = value;
    }

    /**
     * Gets the value of the individualPolicyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualPolicyNumber() {
        return individualPolicyNumber;
    }

    /**
     * Sets the value of the individualPolicyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualPolicyNumber(String value) {
        this.individualPolicyNumber = value;
    }

    /**
     * Gets the value of the secondaryCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryCoverage() {
        return secondaryCoverage;
    }

    /**
     * Sets the value of the secondaryCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryCoverage(String value) {
        this.secondaryCoverage = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the promotionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionNumber() {
        return promotionNumber;
    }

    /**
     * Sets the value of the promotionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionNumber(String value) {
        this.promotionNumber = value;
    }

    /**
     * Gets the value of the socialSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialSecurity() {
        return socialSecurity;
    }

    /**
     * Sets the value of the socialSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialSecurity(String value) {
        this.socialSecurity = value;
    }

    /**
     * Gets the value of the npi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPI() {
        return npi;
    }

    /**
     * Sets the value of the npi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPI(String value) {
        this.npi = value;
    }

    /**
     * Gets the value of the priorAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorAuthorization() {
        return priorAuthorization;
    }

    /**
     * Sets the value of the priorAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorAuthorization(String value) {
        this.priorAuthorization = value;
    }

    /**
     * Gets the value of the mutuallyDefined property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMutuallyDefined() {
        return mutuallyDefined;
    }

    /**
     * Sets the value of the mutuallyDefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMutuallyDefined(String value) {
        this.mutuallyDefined = value;
    }

}
