//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FillStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FillStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Filled" type="{http://www.ncpdp.org/schema/SCRIPT}NoteType"/>
 *         &lt;element name="NotFilled" type="{http://www.ncpdp.org/schema/SCRIPT}DeniedFillType"/>
 *         &lt;element name="PartialFill" type="{http://www.ncpdp.org/schema/SCRIPT}NoteType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FillStatusType", propOrder = {
    "filled",
    "notFilled",
    "partialFill"
})
public class FillStatusType {

    @XmlElement(name = "Filled")
    protected NoteType filled;
    @XmlElement(name = "NotFilled")
    protected DeniedFillType notFilled;
    @XmlElement(name = "PartialFill")
    protected NoteType partialFill;

    /**
     * Gets the value of the filled property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getFilled() {
        return filled;
    }

    /**
     * Sets the value of the filled property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setFilled(NoteType value) {
        this.filled = value;
    }

    /**
     * Gets the value of the notFilled property.
     * 
     * @return
     *     possible object is
     *     {@link DeniedFillType }
     *     
     */
    public DeniedFillType getNotFilled() {
        return notFilled;
    }

    /**
     * Sets the value of the notFilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeniedFillType }
     *     
     */
    public void setNotFilled(DeniedFillType value) {
        this.notFilled = value;
    }

    /**
     * Gets the value of the partialFill property.
     * 
     * @return
     *     possible object is
     *     {@link NoteType }
     *     
     */
    public NoteType getPartialFill() {
        return partialFill;
    }

    /**
     * Sets the value of the partialFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteType }
     *     
     */
    public void setPartialFill(NoteType value) {
        this.partialFill = value;
    }

}
