//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MailboxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MailboxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MailboxID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element name="DeliveredID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *         &lt;element name="AdditionalTraceNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..3" minOccurs="0"/>
 *         &lt;element name="AcknowledgementID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MailboxType", propOrder = {
    "mailboxID",
    "deliveredID",
    "additionalTraceNumber",
    "acknowledgementID"
})
public class MailboxType {

    @XmlElement(name = "MailboxID")
    protected String mailboxID;
    @XmlElement(name = "DeliveredID")
    protected String deliveredID;
    @XmlElement(name = "AdditionalTraceNumber")
    protected String additionalTraceNumber;
    @XmlElement(name = "AcknowledgementID")
    protected String acknowledgementID;

    /**
     * Gets the value of the mailboxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailboxID() {
        return mailboxID;
    }

    /**
     * Sets the value of the mailboxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailboxID(String value) {
        this.mailboxID = value;
    }

    /**
     * Gets the value of the deliveredID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveredID() {
        return deliveredID;
    }

    /**
     * Sets the value of the deliveredID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveredID(String value) {
        this.deliveredID = value;
    }

    /**
     * Gets the value of the additionalTraceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalTraceNumber() {
        return additionalTraceNumber;
    }

    /**
     * Sets the value of the additionalTraceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalTraceNumber(String value) {
        this.additionalTraceNumber = value;
    }

    /**
     * Gets the value of the acknowledgementID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcknowledgementID() {
        return acknowledgementID;
    }

    /**
     * Sets the value of the acknowledgementID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcknowledgementID(String value) {
        this.acknowledgementID = value;
    }

}
