//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MandatoryProviderIDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandatoryProviderIDType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="3">
 *         &lt;element name="NCPDPID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="FileID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="StateLicenseNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicareNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicaidNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="DentistLicenseNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="UPIN" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="FacilityID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PPONumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PayerID" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="ProcessorIdentificationNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="BINLocationNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="Commercial" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MedicalRecordIdentificationNumberEHR" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PatientAccountNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="DEANumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="HIN" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="IndividualPolicyNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="SecondaryCoverage" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="NAICCode" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PromotionNumber" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="SocialSecurity" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="NPI" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="PriorAuthorization" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *         &lt;element name="MutuallyDefined" type="{http://www.ncpdp.org/schema/SCRIPT}an..35M"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryProviderIDType", propOrder = {
    "ncpdpidOrFileIDOrStateLicenseNumber"
})
public class MandatoryProviderIDType {

    @XmlElementRefs({
        @XmlElementRef(name = "MedicaidNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "ProcessorIdentificationNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "FacilityID", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "FileID", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "PatientAccountNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "Commercial", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "SocialSecurity", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "SecondaryCoverage", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "HIN", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "DEANumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "MedicareNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "MedicalRecordIdentificationNumberEHR", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "MutuallyDefined", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "NPI", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "PayerID", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "NAICCode", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "IndividualPolicyNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "PromotionNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "BINLocationNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "PriorAuthorization", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "StateLicenseNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "NCPDPID", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "UPIN", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "DentistLicenseNumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class),
        @XmlElementRef(name = "PPONumber", namespace = "http://www.ncpdp.org/schema/SCRIPT", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> ncpdpidOrFileIDOrStateLicenseNumber;

    /**
     * Gets the value of the ncpdpidOrFileIDOrStateLicenseNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ncpdpidOrFileIDOrStateLicenseNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNCPDPIDOrFileIDOrStateLicenseNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getNCPDPIDOrFileIDOrStateLicenseNumber() {
        if (ncpdpidOrFileIDOrStateLicenseNumber == null) {
            ncpdpidOrFileIDOrStateLicenseNumber = new ArrayList<JAXBElement<String>>();
        }
        return this.ncpdpidOrFileIDOrStateLicenseNumber;
    }

}
