//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ncpdp.org/schema/SCRIPT", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ncpdp.schema.script;
