//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UsernameToken" type="{http://www.ncpdp.org/schema/SCRIPT}UsernameTokenType" minOccurs="0"/>
 *         &lt;element name="Sender" type="{http://www.ncpdp.org/schema/SCRIPT}SecurityIdentificationType"/>
 *         &lt;element name="Receiver" type="{http://www.ncpdp.org/schema/SCRIPT}SecurityIdentificationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityType", propOrder = {
    "usernameToken",
    "sender",
    "receiver"
})
public class SecurityType {

    @XmlElement(name = "UsernameToken")
    protected UsernameTokenType usernameToken;
    @XmlElement(name = "Sender", required = true)
    protected SecurityIdentificationType sender;
    @XmlElement(name = "Receiver", required = true)
    protected SecurityIdentificationType receiver;

    /**
     * Gets the value of the usernameToken property.
     * 
     * @return
     *     possible object is
     *     {@link UsernameTokenType }
     *     
     */
    public UsernameTokenType getUsernameToken() {
        return usernameToken;
    }

    /**
     * Sets the value of the usernameToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsernameTokenType }
     *     
     */
    public void setUsernameToken(UsernameTokenType value) {
        this.usernameToken = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityIdentificationType }
     *     
     */
    public SecurityIdentificationType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityIdentificationType }
     *     
     */
    public void setSender(SecurityIdentificationType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityIdentificationType }
     *     
     */
    public SecurityIdentificationType getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityIdentificationType }
     *     
     */
    public void setReceiver(SecurityIdentificationType value) {
        this.receiver = value;
    }

}
