//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 08:39:59 AM EDT 
//


package org.ncpdp.schema.script;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VerifyStatus" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Code">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}Description" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pharmacy" type="{http://www.ncpdp.org/schema/SCRIPT}OptionalPharmacyType" minOccurs="0"/>
 *         &lt;element name="Prescriber" type="{http://www.ncpdp.org/schema/SCRIPT}HistoryPrescriberType" minOccurs="0"/>
 *         &lt;element name="Facility" type="{http://www.ncpdp.org/schema/SCRIPT}FaciltyType" minOccurs="0"/>
 *         &lt;element name="Patient" type="{http://www.ncpdp.org/schema/SCRIPT}HistoryResponsePatientType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="MedicationDispensed" type="{http://www.ncpdp.org/schema/SCRIPT}MedicationType" maxOccurs="10" minOccurs="0"/>
 *           &lt;element name="MedicationPrescribed" type="{http://www.ncpdp.org/schema/SCRIPT}MedicationType" maxOccurs="10" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "verifyStatus",
    "pharmacy",
    "prescriber",
    "facility",
    "patient",
    "medicationDispensed",
    "medicationPrescribed"
})
@XmlRootElement(name = "Verify")
public class Verify {

    @XmlElement(name = "VerifyStatus")
    protected Verify.VerifyStatus verifyStatus;
    @XmlElement(name = "Pharmacy")
    protected OptionalPharmacyType pharmacy;
    @XmlElement(name = "Prescriber")
    protected HistoryPrescriberType prescriber;
    @XmlElement(name = "Facility")
    protected FaciltyType facility;
    @XmlElement(name = "Patient")
    protected HistoryResponsePatientType patient;
    @XmlElement(name = "MedicationDispensed")
    protected List<MedicationType> medicationDispensed;
    @XmlElement(name = "MedicationPrescribed")
    protected List<MedicationType> medicationPrescribed;

    /**
     * Gets the value of the verifyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Verify.VerifyStatus }
     *     
     */
    public Verify.VerifyStatus getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * Sets the value of the verifyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verify.VerifyStatus }
     *     
     */
    public void setVerifyStatus(Verify.VerifyStatus value) {
        this.verifyStatus = value;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalPharmacyType }
     *     
     */
    public OptionalPharmacyType getPharmacy() {
        return pharmacy;
    }

    /**
     * Sets the value of the pharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalPharmacyType }
     *     
     */
    public void setPharmacy(OptionalPharmacyType value) {
        this.pharmacy = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryPrescriberType }
     *     
     */
    public HistoryPrescriberType getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryPrescriberType }
     *     
     */
    public void setPrescriber(HistoryPrescriberType value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link FaciltyType }
     *     
     */
    public FaciltyType getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaciltyType }
     *     
     */
    public void setFacility(FaciltyType value) {
        this.facility = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link HistoryResponsePatientType }
     *     
     */
    public HistoryResponsePatientType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoryResponsePatientType }
     *     
     */
    public void setPatient(HistoryResponsePatientType value) {
        this.patient = value;
    }

    /**
     * Gets the value of the medicationDispensed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationDispensed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationDispensed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationType }
     * 
     * 
     */
    public List<MedicationType> getMedicationDispensed() {
        if (medicationDispensed == null) {
            medicationDispensed = new ArrayList<MedicationType>();
        }
        return this.medicationDispensed;
    }

    /**
     * Gets the value of the medicationPrescribed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the medicationPrescribed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMedicationPrescribed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MedicationType }
     * 
     * 
     */
    public List<MedicationType> getMedicationPrescribed() {
        if (medicationPrescribed == null) {
            medicationPrescribed = new ArrayList<MedicationType>();
        }
        return this.medicationPrescribed;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.ncpdp.org/schema/SCRIPT}Description" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "description"
    })
    public static class VerifyStatus {

        @XmlElement(name = "Code", required = true)
        protected String code;
        @XmlElement(name = "Description")
        protected String description;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

    }

}
